server:
  port: 8081
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.hongfa.app.relay.*.dao
  type-handlers-package: com.hongfa.app.relay.*.dao
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${dataBaseAddr:172.16.23.16}:${dataBasePort:3306}/${dataBaseName:relay}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${dataBaseUserName:root}
    password: ${dataBaseUserPwd:123456}